import type { NavModule } from './types.js';

export const navModules: NavModule[] = [
  {
    id: 'dashboard',
    label: '工作台',
    shortLabel: '工作台',
    route: '/dashboard/overview',
    stage: 'implemented',
    tabs: [
      { id: 'overview', label: '总览', stage: 'implemented' },
      { id: 'workspaces', label: '工作区', stage: 'implemented' },
      { id: 'activity', label: '最近活动', stage: 'implemented' },
      { id: 'quick-actions', label: '快捷操作', stage: 'implemented' },
    ],
  },
  {
    id: 'chat',
    label: '对话',
    shortLabel: '对话',
    route: '/chat/conversations',
    stage: 'implemented',
    tabs: [
      { id: 'conversations', label: '会话', stage: 'implemented' },
      { id: 'assistants', label: '助手', stage: 'implemented' },
      { id: 'prompt-lab', label: 'Prompt Lab', stage: 'implemented' },
      { id: 'comparison', label: '多模型对比', stage: 'planned' },
      { id: 'artifacts', label: 'Artifacts', stage: 'planned' },
      { id: 'local-history', label: '本地历史', stage: 'implemented' },
    ],
  },
  {
    id: 'models',
    label: '模型',
    shortLabel: '模型',
    route: '/models/providers',
    stage: 'implemented',
    tabs: [
      { id: 'providers', label: '供应商', stage: 'implemented' },
      { id: 'models', label: '模型列表', stage: 'implemented' },
      { id: 'capabilities', label: '能力矩阵', stage: 'implemented' },
      { id: 'templates', label: '参数模板', stage: 'implemented' },
      { id: 'health', label: '健康检测', stage: 'implemented' },
    ],
  },
  {
    id: 'knowledge',
    label: '知识库',
    shortLabel: '知识',
    route: '/knowledge/files',
    stage: 'implemented',
    tabs: [
      { id: 'files', label: '文件', stage: 'implemented' },
      { id: 'bases', label: '知识库', stage: 'implemented' },
      { id: 'retrieval', label: '检索设置', stage: 'planned' },
      { id: 'context', label: '上下文', stage: 'implemented' },
      { id: 'memory', label: '记忆', stage: 'planned' },
    ],
  },
  {
    id: 'tools',
    label: '工具与 Agent',
    shortLabel: '工具',
    route: '/tools/mcp',
    stage: 'implemented',
    tabs: [
      { id: 'tools', label: '工具', stage: 'planned' },
      { id: 'mcp', label: 'MCP', stage: 'implemented' },
      { id: 'agents', label: 'Agent', stage: 'implemented' },
      { id: 'runs', label: '运行中心', stage: 'planned' },
      { id: 'workflow', label: '工作流预留', stage: 'reserved' },
    ],
  },
  {
    id: 'gateway',
    label: '本地网关',
    shortLabel: '网关',
    route: '/gateway/status',
    stage: 'implemented',
    tabs: [
      { id: 'status', label: '网关状态', stage: 'implemented' },
      { id: 'keys', label: 'API Key', stage: 'implemented' },
      { id: 'virtual-models', label: '虚拟模型', stage: 'implemented' },
      { id: 'routes', label: '模型路由', stage: 'implemented' },
      { id: 'integrations', label: '外部接入', stage: 'implemented' },
      { id: 'logs', label: '网关日志', stage: 'implemented' },
    ],
  },
  {
    id: 'data',
    label: '数据配置',
    shortLabel: '数据',
    route: '/data/import',
    stage: 'implemented',
    tabs: [
      { id: 'import', label: '智能导入', stage: 'implemented' },
      { id: 'import-export', label: '导入导出', stage: 'implemented' },
      { id: 'backup', label: '备份恢复', stage: 'implemented' },
      { id: 'snapshots', label: '配置快照', stage: 'implemented' },
      { id: 'cleanup', label: '数据清理', stage: 'implemented' },
    ],
  },
  {
    id: 'settings',
    label: '设置与安全',
    shortLabel: '设置',
    route: '/settings/logs',
    stage: 'implemented',
    tabs: [
      { id: 'request-logs', label: '请求日志', stage: 'implemented' },
      { id: 'usage', label: '用量统计', stage: 'implemented' },
      { id: 'diagnostics', label: '错误诊断', stage: 'implemented' },
      { id: 'evals', label: '模型评测', stage: 'planned' },
      { id: 'keys', label: '密钥安全', stage: 'implemented' },
      { id: 'audit', label: '审计', stage: 'implemented' },
      { id: 'ui', label: '界面设置', stage: 'implemented' },
      { id: 'system', label: '系统设置', stage: 'implemented' },
    ],
  },
];
